name: gethash
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  gethash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get hash of script
        run: echo $(cat stocheck.sh | md5sum | cut -c -32) > hash
