name: gethash
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  getscript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get script

- name: gethash
  uses: DamianReeves/write-file-action@v1.0
  with:
    path: /home/runner/work/stocheck/stocheck/hash
    contents: stocheck.sh | md5sum | cut -c -32
    write-mode: overwrite
